<?php

use App\Http\Controllers\DistractionController;
use App\Http\Controllers\FollowController;
use App\Http\Controllers\HomepageController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\ReactionController;
use Illuminate\Support\Facades\Route;

/*
 * Home page route
 */ 
Route::get('/', [HomepageController::class, 'welcome'])
    ->name('welcome');

/*
 * Used during registration and email verification (initially generated by Laravel Breeze then customized)
 */ 
Route::get('/dashboard', function () {
    return view('dashboard');
})->middleware(['auth', 'verified'])->name('dashboard'); 

/*
 * User's feed of posts by followed users
 */ 
Route::get('/feed', [DistractionController::class, 'following'])->middleware(['auth', 'verified'])->name('following_feed');

/*
 * TODO: add feed of posts made by users that follow the user (we'll call it follower feed))
 * /

/*
 * User CRUD operations (initially generated by Laravel Breeze then customized)
 */ 
Route::middleware('auth')->group(function () {
    Route::get('/profile', [ProfileController::class, 'edit'])->name('profile.edit');
    Route::patch('/profile', [ProfileController::class, 'update'])->name('profile.update');
    Route::delete('/profile', [ProfileController::class, 'destroy'])->name('profile.destroy');
});

/*
 * User profile viewing route
 */
Route::get('/@{username}', [ProfileController::class, 'show'])
    ->name('profile');

/*
 * Distraction post route
 */
Route::post('/distractions', [DistractionController::class, 'store'])->name('distractions.store');

/*
 * TODO: Add direct route to distraction 
 */
//Route::get('/distractions/{distraction}', [DistractionController::class, 'show'])->name('distractions.show');

/*
 * Follow/Unfollow routes
 */
Route::middleware('auth')->group(function () {
    Route::post('/user/{user}/follow', [FollowController::class, 'follow'])->name('follow');
    Route::delete('/user/{user}/unfollow', [FollowController::class, 'unfollow'])->name('unfollow');
});

/*
 * react/unreact routes
 */
Route::post('/distractions/{distraction}/react', [ReactionController::class, 'toggle'])
    ->middleware('auth')
    ->name('reactions.toggle');



require __DIR__.'/auth.php';
